### ISSUE TITLE
import for utils-* pachages doesnt work

### ISSUE THREAD

**Issue by VictorEffectiv** [mkosir/turborepo-boilerplate#1]
### Description

I dont if its related to my node version but for some reason i cannot start dev because TS is complaining that it is not able to find any of the packages that start with `util` but still gives them to me as an option in the autocomplete.

![image](https://user-images.githubusercontent.com/100563134/216953288-bc300099-a4e7-461e-b867-1cbd63f4ab07.png)
![image](https://user-images.githubusercontent.com/100563134/216953345-b972d4f5-db70-42bb-b2e4-eee0e260835d.png)

### Additional Information

I am on windows11, nodev16, and npm v8

**Comment by mkosir** [comment]
Hey @VictorEffectiv , can you try to run `npm run build` first (will add it to readme)?

**Comment by VictorEffectiv** [comment]
@mkosir thank you for the tip. now i can run `dev` without problems, but i still get this lint erros

![image](https://user-images.githubusercontent.com/100563134/216984587-593c9e73-dcf1-4c87-9f16-2e49365674d0.png)
![image](https://user-images.githubusercontent.com/100563134/216984645-81d536d3-ab7b-4e3d-839e-9d0b494700a6.png)

**Comment by VictorEffectiv** [comment]
nevermind, after closing visual studio code and reopening again, now i dont get any error. I will close this issue.Thank you for youre hard work.
